/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package com.citypay.pos.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class TransactionResult (
  /* A description of the status of a transaction */
  status: Option[String],
  /* The indentifier uniquely identifying the transaction */
  identifier: Option[String],
  /* A boolean value stating whether the transaction has completed. The value will be false if the transaction is in progress. Should the value be true, a property containing the transaction details is made available. */
  isComplete: Option[Boolean],
  data: Option[TransactionData]
) extends ApiModel


